"""add conversation title, pinned flag and created_at index

Revision ID: 56024be753fd
Revises: 8902a22e4ce3
Create Date: 2026-10-04 08:45:20.750118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56024be753fd'
down_revision: Union[str, Sequence[str], None] = '8902a22e4ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('title', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_column('conversations', 'pinned')
    op.drop_column('conversations', 'title')
    # ### end Alembic commands ###
